Repository flowjs/flow.js, pull requests merged in 2021-09, with the labels that each got.

#351 FlowChunk: xhr abort fixes
  src/FlowChunk.js
Labels: v3

#350 assignBrowse / onDrop: Consider the possibility of an async initFileFn
  src/Flow.js
Labels: v3

#348 Improvements to chunks coming from a stream/async reader
  dist/flow.js
  dist/flow.min.js
  src/AsyncFlowFile.js
  src/FlowChunk.js
  test/asyncSpec.js
  test/helpers.js
  test/uploadSpec.js
Labels: enhancement, v3

#358 Unduplicate a file-added hook
  src/AsyncFlowFile.js
Labels: bug
